Fix build issues on arch Linux
* Add QObject include in CommandProcess.h
  This solves compilation error:

  'src/CommandProcess.h:25:2: error: ‘Q_OBJECT’ does not name a type'

  This is probably due to newer Qt version used by arch linux
  The QtObject header seems available at least since Qt 4, if older
  versions need to be supported this could be changed to qobject.h
  depending on the Qt library version detected

* Improve hm.sh to detect if python2 is explicitly available
  and use it to try to avoid using python3, which is unsupported
  by the hm.py script